<?xml version="1.0" encoding="UTF-8"?>
<!--
  ContributionToAllocationMap.xsl
  ================================
  This XSLT represents the output that the BizTalk Mapper tool generates from
  ContributionToAllocationMap.btm when the map is compiled.

  Functoids used:
    ID 1 – String Concatenate  : AllocationId = "FA-" + ContributionId
    ID 2 – String Constant     : AllocationStatus = "PENDING" (per-member)
    ID 3 – Scripting Functoid  : FormatABN(EmployerABN) → EmployerDetails/ABN
    ID 4 – Scripting Functoid  : CalculateNetContribution(GrossAmount) → ContributionAmount

  The <msxsl:script> block below contains the inline C# code that BizTalk embeds
  when the Scripting Functoid is configured in "Inline C#" mode.
  (When "External Assembly" mode is used, BizTalk instead calls the compiled
  ContributionMapHelper class via an XSLT extension object.)
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:msxsl="urn:schemas-microsoft-com:xslt"
  xmlns:var="http://schemas.microsoft.com/BizTalk/2003/var"
  xmlns:userCsharp="http://schemas.microsoft.com/BizTalk/2003/userCSharp"
  xmlns:src="http://SuperFundManagement.Schemas.SuperContribution"
  xmlns:tgt="http://SuperFundManagement.Schemas.FundAllocation"
  exclude-result-prefixes="msxsl var userCsharp src">

  <xsl:output method="xml" omit-xml-declaration="yes" indent="yes" />

  <!-- ═══════════════════════════════════════════════════════════════════════
       Inline C# scripting block — generated by BizTalk for Scripting Functoids
       3 (FormatABN) and 4 (CalculateNetContribution).

       In a real BizTalk build this block is embedded verbatim in the compiled
       .xsl file.  The msxsl:script extension is processed by the .NET XSLT
       engine (XslTransform / XslCompiledTransform) at run time.
  ═══════════════════════════════════════════════════════════════════════ -->
  <msxsl:script language="C#" implements-prefix="userCsharp">
    <![CDATA[
    using System;
    using System.Text.RegularExpressions;

    // ── Scripting Functoid 3 ─────────────────────────────────────────────────
    // Called in the XSLT template below to transform the raw EmployerABN value
    // into the standard "XX XXX XXX XXX" display format before writing it to
    // the EmployerDetails/ABN element in the output document.
    public string FormatABN(string abn)
    {
        if (string.IsNullOrWhiteSpace(abn))
            return abn ?? string.Empty;

        // Strip any existing spaces or hyphens
        string digits = Regex.Replace(abn, @"[\s\-]", string.Empty);

        // Must be exactly 11 numeric digits to format
        if (digits.Length != 11 || !Regex.IsMatch(digits, @"^\d{11}$"))
            return abn;

        return string.Format("{0} {1} {2} {3}",
            digits.Substring(0, 2),
            digits.Substring(2, 3),
            digits.Substring(5, 3),
            digits.Substring(8, 3));
    }

    // ── Scripting Functoid 4 ─────────────────────────────────────────────────
    // Called in the XSLT for-each loop below to convert each member's GrossAmount
    // into the net contribution amount after deducting 15% contributions tax.
    // The result is written to Allocation/ContributionAmount.
    public string CalculateNetContribution(string grossAmountStr)
    {
        decimal gross;
        if (!decimal.TryParse(grossAmountStr,
                System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture,
                out gross))
        {
            return "0.00";
        }

        const decimal contributionsTaxRate = 0.15m;
        decimal net = Math.Round(gross * (1m - contributionsTaxRate), 2,
                                 MidpointRounding.AwayFromZero);
        return net.ToString("0.00",
                            System.Globalization.CultureInfo.InvariantCulture);
    }
    ]]>
  </msxsl:script>

  <!-- ═══════════════════════════════════════════════════════════════════════
       Root template — processes the SuperContributionRequest document root
  ═══════════════════════════════════════════════════════════════════════ -->
  <xsl:template match="/">
    <xsl:apply-templates select="/src:SuperContributionRequest" />
  </xsl:template>

  <xsl:template match="/src:SuperContributionRequest">
    <tgt:FundAllocationInstruction>

      <!-- Functoid 1: String Concatenate → AllocationId = "FA-" + ContributionId -->
      <tgt:AllocationId>
        <xsl:value-of select="concat('FA-', src:ContributionId)" />
      </tgt:AllocationId>

      <!-- Direct link L02: ContributionId → SourceContributionRef -->
      <tgt:SourceContributionRef>
        <xsl:value-of select="src:ContributionId" />
      </tgt:SourceContributionRef>

      <tgt:EmployerDetails>
        <!-- Direct link L03 -->
        <tgt:EmployerId>
          <xsl:value-of select="src:EmployerId" />
        </tgt:EmployerId>

        <!-- Direct link L04 -->
        <tgt:EmployerName>
          <xsl:value-of select="src:EmployerName" />
        </tgt:EmployerName>

        <!-- Scripting Functoid 3: FormatABN(EmployerABN) → ABN -->
        <tgt:ABN>
          <xsl:value-of select="userCsharp:FormatABN(string(src:EmployerABN))" />
        </tgt:ABN>
      </tgt:EmployerDetails>

      <!-- Direct link L06: PayPeriodEndDate → AllocationDate -->
      <tgt:AllocationDate>
        <xsl:value-of select="src:PayPeriodEndDate" />
      </tgt:AllocationDate>

      <tgt:MemberAllocations>
        <!-- Looping functoid L07: Member → Allocation (one output element per input Member) -->
        <xsl:for-each select="src:Members/src:Member">
          <tgt:Allocation>
            <!-- Direct link L08 -->
            <tgt:AccountNumber>
              <xsl:value-of select="src:MemberAccountNumber" />
            </tgt:AccountNumber>

            <!-- Direct link L09 -->
            <tgt:MemberName>
              <xsl:value-of select="src:MemberName" />
            </tgt:MemberName>

            <!-- Direct link L10 -->
            <tgt:ContributionType>
              <xsl:value-of select="src:ContributionType" />
            </tgt:ContributionType>

            <!-- Scripting Functoid 4: CalculateNetContribution(GrossAmount) → ContributionAmount -->
            <tgt:ContributionAmount>
              <xsl:value-of select="userCsharp:CalculateNetContribution(string(src:GrossAmount))" />
            </tgt:ContributionAmount>

            <!-- Functoid 2: String Constant → AllocationStatus = "PENDING" -->
            <tgt:AllocationStatus>PENDING</tgt:AllocationStatus>
          </tgt:Allocation>
        </xsl:for-each>
      </tgt:MemberAllocations>

      <!-- Direct link L13: TotalContribution → TotalAllocated -->
      <tgt:TotalAllocated>
        <xsl:value-of select="src:TotalContribution" />
      </tgt:TotalAllocated>

      <!-- Direct link L14: Currency → CurrencyCode -->
      <tgt:CurrencyCode>
        <xsl:value-of select="src:Currency" />
      </tgt:CurrencyCode>

      <!-- Constant "PENDING" → Status -->
      <tgt:Status>PENDING</tgt:Status>

    </tgt:FundAllocationInstruction>
  </xsl:template>

</xsl:stylesheet>
